# Generated by Django 4.2.15 on 2024-12-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AmendatoryList",
            fields=[
                ("ammendatory_id", models.AutoField(primary_key=True, serialize=False)),
                ("requesting_office_a", models.CharField(max_length=255)),
                (
                    "total_amount_a",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("requesting_office_b", models.CharField(max_length=255)),
                (
                    "total_amount_b",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("particulars_item_description", models.TextField()),
                ("reason_for_amending", models.TextField()),
                ("validator", models.CharField(max_length=255)),
                ("date_advance_copy", models.DateField()),
                ("date_signed", models.DateField()),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
