# Generated by Django 3.2.6 on 2024-05-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TSDReceivingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_number', models.CharField(max_length=100)),
                ('project_title', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('abc', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('aoname', models.CharField(max_length=100)),
                ('fundyear', models.CharField(max_length=100)),
                ('fund_source', models.CharField(max_length=100)),
                ('object_of_expenditure', models.CharField(max_length=100)),
                ('validator', models.CharField(max_length=100)),
                ('canvasser', models.CharField(max_length=100)),
            ],
        ),
    ]
