# Generated by Django 3.2.6 on 2024-06-20 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalServicesDivision', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tsdreceivingform',
            name='project_number',
        ),
    ]
