# Generated by Django 3.2.6 on 2024-06-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfrastructureCommittee', '0003_auto_20240620_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infrastructurecommittee',
            name='abc',
        ),
        migrations.RemoveField(
            model_name='infrastructurecommittee',
            name='bid_amount',
        ),
        migrations.RemoveField(
            model_name='infrastructurecommittee',
            name='calendar_days',
        ),
        migrations.RemoveField(
            model_name='infrastructurecommittee',
            name='duration',
        ),
        migrations.AlterField(
            model_name='infrastructurecommittee',
            name='remarks',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
