# Generated by Django 3.2.6 on 2024-06-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_code', models.CharField(blank=True, max_length=255, null=True)),
                ('project_number', models.CharField(blank=True, max_length=255, null=True)),
                ('project_title', models.CharField(blank=True, max_length=255, null=True)),
                ('project_type', models.CharField(blank=True, max_length=255, null=True)),
                ('abc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('early_procurement', models.BooleanField(default=False)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('calendar_days', models.IntegerField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_of_procurement', models.CharField(blank=True, max_length=255, null=True)),
                ('pre_bid_date', models.DateField(blank=True, null=True)),
                ('fund_source', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('mode', models.CharField(blank=True, max_length=255, null=True)),
                ('bid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pre_proc_date', models.DateField(blank=True, null=True)),
                ('itb_date', models.DateField(blank=True, null=True)),
                ('bidding_date', models.DateField(blank=True, null=True)),
                ('bid_eval_date', models.DateField(blank=True, null=True)),
                ('post_qua', models.DateField(blank=True, null=True)),
                ('reso_date', models.DateField(blank=True, null=True)),
                ('noa_date', models.DateField(blank=True, null=True)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('np_start', models.DateField(blank=True, null=True)),
                ('np_end', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
