# Generated by Django 3.2.6 on 2024-07-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfrastructureCommittee', '0005_auto_20240620_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructurecommittee',
            name='key_personnel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='infrastructurecommittee',
            name='major_equipment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
