# Generated by Django 4.2.15 on 2024-11-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("InfrastructureCommittee", "0006_auto_20240702_1755"),
    ]

    operations = [
        migrations.AlterField(
            model_name="infrastructurecommittee",
            name="project_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
