# Generated by Django 3.2.6 on 2024-06-20 18:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TechnicalServicesDivision', '0002_remove_tsdreceivingform_project_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNumbers',
            fields=[
                ('project_unique_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_number', models.CharField(max_length=100, unique=True)),
                ('project_title', models.CharField(max_length=100)),
                ('tsd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TechnicalServicesDivision.tsdreceivingform')),
            ],
        ),
    ]
