# Generated by Django 3.2.6 on 2024-04-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserAuthentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='employee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
