# Generated by Django 3.2.6 on 2024-05-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivingForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pd_routing_number', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('received_by', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('office_code', models.CharField(max_length=50)),
                ('end_user', models.CharField(max_length=100)),
                ('document_type', models.CharField(max_length=100)),
                ('program', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('division_assigned', models.CharField(max_length=100)),
                ('date_received', models.DateField(auto_now_add=True)),
                ('time_received', models.TimeField(auto_now_add=True)),
                ('transmitted_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
