# Generated by Django 3.2.6 on 2024-05-02 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdministrationDepartment', '0002_remove_receivingform_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivingform',
            name='division_assigned',
        ),
    ]
